apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        root /app;
        index index.html;
        include /etc/nginx/mime.types;
        location / {
          proxy_pass http://frontend/;
            try_files $uri $uri/ /;
        }
        location /jenkins/ {
            proxy_pass http://jenkins:8080;
    		proxy_read_timeout  90;
    		proxy_set_header X-Forwarded-Host $host:$server_port;
    		proxy_set_header X-Forwarded-Server $host;
    		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    		proxy_set_header X-Forwarded-Proto $scheme;
    		proxy_set_header X-Real-IP $remote_addr;
        }
    }
